### ISSUE TITLE
why are there 2 collated folders?

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W09-B3/main#117]
@eldriclim @dalessr @ZhangH795 @Pengyuz  for your attention

**Comment by dalessr** [comment]
Actually we are also confused about that. We can see only one folder in our local repo, but it becomes two after merging.

**Comment by okkhoy** [comment]
need to fix the issue, else, our scripts may not pick up the right one

**Comment by okkhoy** [comment]
either @Pengyuz  is at fault or the rest 3 of you. 
please take a look at the contents of the collated folders

**Comment by dalessr** [comment]
Okay we have fixed that already. Thanks!
