### ISSUE TITLE
code quality comments for ZhangH795

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W09-B3/main#121]
![image](https://user-images.githubusercontent.com/1023494/32640607-7b40d1a0-c604-11e7-9e92-034fa1cf4a94.png)
- try to give a brief description of what the method does. it is not very useful to have only param and return in the header comments

![image](https://user-images.githubusercontent.com/1023494/32640623-961fc99a-c604-11e7-85bc-fd1cc6bdb9d9.png)
![image](https://user-images.githubusercontent.com/1023494/32640658-bddcbf4c-c604-11e7-99d5-8799ec297c7d.png)
- please improve the spacing; at the moment it looks like a blob of code

- you have a few long lines. see if you can split them to improve readability

@ZhangH795  fya

**Comment by ZhangH795** [comment]
Thank you so much for your comment.
