### ISSUE TITLE
code quality comments for dalessr

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W09-B3/main#122]
![image](https://user-images.githubusercontent.com/1023494/32640741-14645ea6-c605-11e7-876c-c7a341b7b980.png)
![image](https://user-images.githubusercontent.com/1023494/32640754-1e7e2282-c605-11e7-91cb-6ddcbc3324e5.png)
![image](https://user-images.githubusercontent.com/1023494/32640764-29448544-c605-11e7-8cf0-b5bffaafb0a0.png)
- header comments do not follow the convention we specify. ` Returns ... ` is a better way of writing it

![image](https://user-images.githubusercontent.com/1023494/32640794-59630a98-c605-11e7-89d2-d1e6356c9b47.png)
- eliminate these not-very-useful comments

![image](https://user-images.githubusercontent.com/1023494/32640817-7904168a-c605-11e7-8b8d-1785d3e7a1d4.png)
- try to split these to multiple lines for better readability

@dalessr FYA

**Comment by dalessr** [comment]
I will pay attention to it. Thanks a lot!
