### ISSUE TITLE
code quality comments for eldriclim

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W09-B3/main#123]
![image](https://user-images.githubusercontent.com/1023494/32640858-beb3cc48-c605-11e7-9442-a56ce6664828.png)
- (above and many methods/classes that follow) header comments do not follow the convention we specify 

![image](https://user-images.githubusercontent.com/1023494/32640980-64e429e6-c606-11e7-84c0-eb86b18c8db9.png)
- the above method seems to have very similar code blocks (I haven't delved deep in to the logic, so I may be wrong as well)

@eldriclim FYA

**Comment by eldriclim** [comment]
Thank you for the pointers, I'll be working on it over the weekend.
