### ISSUE TITLE
code quality comments for Pengyuz

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W09-B3/main#124]
![image](https://user-images.githubusercontent.com/1023494/32641039-aaee97fa-c606-11e7-857c-49fde4b7f94a.png)
- (above and some other methods that follow) header comment doesn't follow the convention we specify

![image](https://user-images.githubusercontent.com/1023494/32641045-b95e7b8e-c606-11e7-9ad7-9c3840271417.png)
- how do we name boolean variables?

![image](https://user-images.githubusercontent.com/1023494/32641080-f6f9f5fe-c606-11e7-907e-e58eca1846d5.png)
![image](https://user-images.githubusercontent.com/1023494/32641083-0044b3a6-c607-11e7-9cc9-4b9f66b857d2.png)
- can improve SLAP

@Pengyuz FYA

**Comment by Pengyuz** [comment]
Thank you for your suggestion. I will work on it.
